export BIN=$HOME/Documents/bin
export JAVA_HOME=$BIN/zulu8.17.0.3-jdk8.0.102-win_x64
export MVN_HOME=$BIN/apache-maven-3.3.9
export ANDROID_STUDIO_HOME=$BIN/android-studio
export ANDROID_HOME=$BIN/android-sdk
export RUBY_HOME=$BIN/Ruby23-x64
export SUBL_HOME=$BIN/"Sublime Text 2.0.2 x64"
export PATH=$RUBY_HOME/bin:$PATH
export PATH=$JAVA_HOME/bin:$MVN_HOME/bin:$PATH
export PATH=$ANDROID_STUDIO_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
export PATH=$SUBL_HOME:$PATH
